stages:
    - build
    - test

variables:
    IMAGE_NAME: publisher_service
    DOCKER_DRIVER: overlay2
    IMAGE_TAG: $CI_COMMIT_SHA

build image:
    tags:
        - building
    stage: build
    cache:
        paths:
            - .docker/cache
    script:
        - docker build -t ${IMAGE_NAME}:${IMAGE_TAG} -t ${IMAGE_NAME}:latest .
        - docker image prune -f
    when: manual
    allow_failure: false

test run:
    tags:
        - testing
    stage: test
    needs:
        - build image
    script:
        - docker run --rm -d --name ${IMAGE_NAME} ${IMAGE_NAME}
    allow_failure: false